// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManager.API.Data;

#nullable disable

namespace TaskManager.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250910205106_SeedTasks")]
    partial class SeedTasks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("TaskManager.API.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Practice C# basics",
                            DueDate = new DateTime(2025, 9, 13, 23, 51, 6, 901, DateTimeKind.Local).AddTicks(2650),
                            IsCompleted = false,
                            Title = "Learn C#"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Create first Web API",
                            DueDate = new DateTime(2025, 9, 15, 23, 51, 6, 901, DateTimeKind.Local).AddTicks(2710),
                            IsCompleted = false,
                            Title = "Build API"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
